---
name: Molecule tests
on: ['create','pull_request']
jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python_version: ['3.10','3.11']
        #{{ cookiecutter.role_name }}_version: []
    steps:
      - name: Check-out repository
        uses: actions/checkout@v4
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install podman buildah
      - name: Install Python ${{ matrix.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install required Python packages
        run: |
          pip3 install -r requirements.txt
      - name: Run Molecule tests
        run: |
          molecule test --all