---
name: Molecule tests
on: ['push','pull_request']
jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python_version: ['3.10','3.11']
    steps:
      - name: Check-out repository
        uses: actions/checkout@v4
        with:
          path: {{ cookiecutter.role_name }}
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install podman buildah
      - name: Install Python {% raw %}${{ matrix.python_version }}{% endraw %}
        uses: actions/setup-python@v4
        with:
          python-version: {% raw %}${{ matrix.python_version }}{% endraw %}
      - name: Install required Python packages
        working-directory: {{ cookiecutter.role_name }}
        run: |
          pip3 install -r requirements.txt
      - name: Run Molecule tests
        working-directory: {{ cookiecutter.role_name }}
        run: |
          molecule test --all