---
dependency:
  name: galaxy
  options:
    requirements-file: molecule/requirements.yml
driver:
  name: podman
platforms:
  - name: default
    image: docker.io/fbn587/molecule-ubuntu:jammy
    pre_build_image: true
    command: /sbin/init
    systemd: always
provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: profile_tasks, timer, yaml
  inventory:
    links:
      group_vars: inventory/group_vars/
      #host_vars: inventory/host_vars/
verifier:
  name: ansible
